theme: jekyll-theme-cayman

# This is Search Engine Optimization. It'll help website look better on search.
seo:
  title:       "Konect'Eirb| An ENSEIRB-MATMECA project"
  description: "Student-run network deployment of connected objects in order to dispense with operator networks"
  #image:       ""
  
